let course=null,mode=null,index=0,score=0,questions=[],current=null,recognition=null,recording=false,photo=null;
const COURSE={bricklaying:"Bricklaying",siteCarpentry:"Site Carpentry",benchJoinery:"Bench Joinery"};
const store=JSON.parse(localStorage.getItem("epa-practice")||"{}");
const $=s=>document.querySelector(s);
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function records(){return EPA_QUESTIONS[course]||[]}
function shell(body){$("#app").innerHTML='<main class="shell">'+body+'</main>';bind()}
function badge(k){const t=k[0]==="K"?"Knowledge":k[0]==="S"?"Skill":"Behaviour";return '<span class="ksb-badge '+k[0].toLowerCase()+'"><b>'+esc(k)+'</b><span>'+t+'</span></span>'}
function home(){shell('<header class="top"><div class="brand"><div class="mark">EPA</div><div><div class="eyebrow">Practice</div><div class="title">EPA Practice</div></div></div></header><section class="hero"><div class="eyebrow">End-point assessment preparation</div><h1>Practise with<br>purpose.</h1><p>Focused EPA practice for construction apprentices. Every question tests one K, S or B at a time.</p></section><div class="grid">'+Object.keys(COURSE).map(k=>'<button class="card course" data-course="'+k+'"><span class="pill">'+(k==="bricklaying"?"ST0095":"Apprenticeship")+'</span><h2>'+COURSE[k]+'</h2><p>'+recordsFor(k).length+' individual KSB questions.</p><span class="muted">Open practice <span class="arrow">→</span></span></button>').join("")+'</div><div class="footer">Practice support only — not an official EPA result.</div>')}
function recordsFor(k){return EPA_QUESTIONS[k]||[]}
function courseHome(){const h=store[course]||{m:0,d:0,p:0};const ready=Math.round((h.m||0)*.4+(h.d||0)*.3+(h.p||0)*.3);shell('<button class="btn ghost" data-home>‹ Courses</button><header class="course-head"><div><div class="eyebrow">Selected course</div><div class="title">'+COURSE[course]+'</div></div><span class="pill">'+records().length+' KSB questions</span></header><div class="card readiness"><div><div class="eyebrow">Practice readiness</div><div class="readiness-number">'+ready+'%</div></div><div class="bar"><i style="width:'+ready+'%"></i></div><p class="muted">A practice indicator based on recorded activity. It is not a pass/fail decision.</p></div><div class="modules"><button class="card module" data-mode="mcq"><span class="tag">01</span><h3>Question Challenge</h3><p>20 questions. Each question targets exactly one K, S or B.</p><span class="muted">Start challenge <span class="arrow">→</span></span></button><button class="card module" data-mode="discussion"><span class="tag">02</span><h3>Professional Discussion</h3><p>Talk through an EPA-style question and receive practice feedback.</p><span class="muted">Start discussion <span class="arrow">→</span></span></button><button class="card module" data-mode="practical"><span class="tag">03</span><h3>Practical Test</h3><p>Workshop checklist with measurements, tolerances, safety and photo review.</p><span class="muted">Start practical <span class="arrow">→</span></span></button></div>')}
function questionCard(q,showAnswers=true){return '<div class="qmeta"><span>QUESTION '+(index+1)+' OF '+questions.length+'</span>'+badge(q[0])+'</div><div class="card question-card"><div class="question-focus"><div class="eyebrow">'+(q[0][0]==="K"?"KNOWLEDGE":q[0][0]==="S"?"SKILL":"BEHAVIOUR")+' · '+esc(q[0])+'</div><h1>'+esc(q[1])+'</h1></div>'+(showAnswers?'<div class="answers">'+shuffle(q[2]).map((o,i)=>'<button class="answer" data-answer="'+encodeURIComponent(o)+'"><span class="letter">'+String.fromCharCode(65+i)+'</span><span>'+esc(o)+'</span></button>').join("")+'</div>':"")+'</div>'}
function mcq(){if(index>=questions.length){const pct=Math.round(score/questions.length*100);store[course]??={};store[course].m=Math.max(store[course].m||0,pct/100);localStorage.setItem("epa-practice",JSON.stringify(store));shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><section class="hero result"><div class="eyebrow">Challenge complete</div><h1>'+score+' / '+questions.length+'</h1><p>Your practice score was '+pct+'%.</p></section><div class="card result-card"><div class="stats"><div class="stat"><b>'+pct+'%</b><span>Score</span></div><div class="stat"><b>'+questions.length+'</b><span>Questions</span></div><div class="stat"><b>'+records().length+'</b><span>KSB questions</span></div></div><button class="btn" data-mode="mcq">New challenge</button></div>');return}const q=current=questions[index];shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><div class="question">'+questionCard(q)+'</div>')}
function discussion(){current=current||shuffle(records())[0];shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><div class="question"><div class="qmeta"><span>PROFESSIONAL DISCUSSION</span>'+badge(current[0])+'</div><div class="card question-card"><div class="eyebrow">'+(current[0][0]==="K"?"KNOWLEDGE":current[0][0]==="S"?"SKILL":"BEHAVIOUR")+' · '+esc(current[0])+'</div><h1>'+esc(current[1])+'</h1><p class="muted">Explain your answer as you would in a professional discussion. Give reasons, refer to safe working practices and use relevant technical terminology where appropriate.</p><div class="audio"><button class="mic" id="mic">'+(recording?"■":"●")+'</button><div class="muted">'+(recording?"Listening… tap to stop":"Tap to answer by voice")+'</div></div><textarea id="answer" placeholder="Your spoken answer will appear here. You can also type or edit it.">'+esc(current.answer||"")+'</textarea><div class="row between"><button class="btn secondary" id="speak">Read question aloud</button><button class="btn" id="ai">Get AI feedback</button></div>'+(current.feedback?'<div class="feedback"><b>AI feedback</b><br>'+esc(current.feedback)+'</div>':"")+'</div></div>')}
function practical(){current=current||shuffle(records())[0];shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><div class="sectionhead"><div><div class="eyebrow">PRACTICAL TEST</div><h2>'+badge(current[0])+'</h2><p class="muted">'+esc(current[1])+'</p></div></div><div class="practical"><div class="card"><div class="notice">Complete this as a workshop practice task. Follow your college/employer RAMS, drawings, specifications and manufacturer instructions.</div>'+["Confirm drawing/specification, task and required tolerances before starting.","Identify PPE, safety controls, tools and materials; check condition and suitability.","Set out and record critical measurements, levels, angles, centres or gauge information.","Complete the task using the correct sequence and construction/manufacturing technique.","Inspect the finished work against the drawing/specification and record any defects or adjustments.","Leave the work area, tools and materials safe, clean and correctly stored."].map((x,i)=>'<label class="check"><input type="checkbox"><span><b>'+(i+1)+'.</b> '+x+'</span></label>').join("")+'<div class="row" style="margin-top:18px"><button class="btn" id="donePractical">Complete practice</button><button class="btn secondary" id="nextPractical">Next task</button></div></div><div class="card"><div class="tag">Photo review</div><h3>Show the finished work</h3><p class="muted">AI feedback describes only what can be seen and identifies checks that cannot be verified from a photograph.</p><div class="photo"><input id="photoInput" type="file" accept="image/*" capture="environment"><div id="preview"></div></div><button class="btn" style="margin-top:12px;width:100%" id="photoAI">Review photo with AI</button><div id="photoFeedback"></div></div></div>')}
function bind(){document.querySelectorAll("[data-course]").forEach(b=>b.onclick=()=>{course=b.dataset.course;courseHome()});document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>start(b.dataset.mode));document.querySelectorAll("[data-home]").forEach(b=>b.onclick=home);document.querySelectorAll("[data-course-home]").forEach(b=>b.onclick=courseHome);document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const picked=decodeURIComponent(b.dataset.answer);const ok=picked===current[2][0];b.classList.add(ok?"correct":"wrong");if(ok)score++;document.querySelectorAll("[data-answer]").forEach(x=>x.disabled=true);setTimeout(()=>{index++;mcq()},450)});$("#mic")?.addEventListener("click",toggleSpeech);$("#speak")?.addEventListener("click",()=>speak(current[1]));$("#ai")?.addEventListener("click",ai);$("#answer")?.addEventListener("input",e=>current.answer=e.target.value);$("#donePractical")?.addEventListener("click",()=>{store[course]??={};store[course].p=Math.min(1,(store[course].p||0)+.1);localStorage.setItem("epa-practice",JSON.stringify(store));courseHome()});$("#nextPractical")?.addEventListener("click",()=>{current=shuffle(records())[0];practical()});$("#photoInput")?.addEventListener("change",photoPick);$("#photoAI")?.addEventListener("click",photoReview)}
function start(m){mode=m;index=0;score=0;current=null;if(m==="mcq"){questions=shuffle(records()).slice(0,20);mcq()}else if(m==="discussion"){current=shuffle(records())[0];discussion()}else{current=shuffle(records())[0];practical()}}
function speak(t){if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="en-GB";u.rate=.92;speechSynthesis.speak(u)}}
function toggleSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Voice transcription is not supported in this browser. Type your answer instead.");return}if(recording){recognition?.stop();recording=false;discussion();return}recognition=new SR();recognition.lang="en-GB";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let s="";for(let i=0;i<e.results.length;i++)s+=e.results[i][0].transcript+" ";current.answer=s.trim();const a=$("#answer");if(a)a.value=current.answer};recognition.onend=()=>{recording=false;discussion()};recording=true;recognition.start();discussion()}
async function ai(){if(!current.answer?.trim()){alert("Answer the question first.");return}current.feedback="Analysing your answer…";discussion();try{const r=await fetch("/api/ai-feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({course:COURSE[course],ksb:current[0],question:current[1],answer:current.answer})});const d=await r.json();current.feedback=d.feedback||d.error||"No feedback returned.";store[course]??={};store[course].d=Math.min(1,(store[course].d||0)+.1);localStorage.setItem("epa-practice",JSON.stringify(store));discussion()}catch(e){current.feedback="AI feedback needs the server endpoint configured. Your transcript remains available on this device.";discussion()}}
function photoPick(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{photo=r.result;$("#preview").innerHTML='<img src="'+r.result+'" alt="Practical work preview">'};r.readAsDataURL(f)}
async function photoReview(){if(!photo){alert("Take or select a photo first.");return}$("#photoFeedback").innerHTML='<div class="feedback">Analysing photo…</div>';try{const r=await fetch("/api/ai-feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({course:COURSE[course],ksb:current[0],task:current[1],image:photo})});const d=await r.json();$("#photoFeedback").innerHTML='<div class="feedback"><b>AI practical review</b><br>'+esc(d.feedback||d.error||"No feedback returned.")+'</div>'}catch(e){$("#photoFeedback").innerHTML='<div class="feedback">AI photo review needs the server endpoint configured.</div>'}}
home();
