let course=null,mode=null,index=0,score=0,questions=[],current=null;
const COURSE={bricklaying:"Bricklaying",siteCarpentry:"Site Carpentry",benchJoinery:"Bench Joinery"};
const store=JSON.parse(localStorage.getItem("epa-practice")||"{}");
const $=s=>document.querySelector(s);
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function records(){return EPA_QUESTIONS[course]||[]}
function shell(body){$("#app").innerHTML='<main class="shell">'+body+"</main>";bind()}
function badge(k){const t=k[0]==="K"?"Knowledge":k[0]==="S"?"Skill":"Behaviour";return '<span class="ksb-badge '+k[0].toLowerCase()+'"><b>'+esc(k[0])+'</b><span>'+t+"</span></span>"}
function home(){shell('<header class="top"><div class="brand"><div class="mark">EPA</div><div><div class="eyebrow">Practice</div><div class="title">EPA Practice</div></div></div></header><section class="hero"><div class="eyebrow">End-point assessment preparation</div><h1>Practise with<br>purpose.</h1><p>Focused EPA practice for construction apprentices. Every question tests one K, S or B at a time.</p></section><div class="grid">'+Object.keys(COURSE).map(k=>'<button class="card course" data-course="'+k+'"><span class="pill">'+(k==="bricklaying"?"ST0095":"ST0264")+'</span><h2>'+COURSE[k]+'</h2><p>'+recordsFor(k).length+" individual KSB questions.</p><span class="muted">Open practice <span class="arrow">→</span></span></button>").join("")+'</div><div class="footer">Practice support only — not an official EPA result.</div>')}
function recordsFor(k){return EPA_QUESTIONS[k]||[]}
function courseHome(){const h=store[course]||{m:0,d:0,p:0};const ready=Math.round((h.m||0)*.4+(h.d||0)*.3+(h.p||0)*.3);shell('<button class="btn ghost" data-home>‹ Courses</button><header class="course-head"><div><div class="eyebrow">Selected course</div><div class="title">'+COURSE[course]+'</div></div><span class="pill">'+records().length+" KSB questions</span></header><div class="card readiness"><div><div class="eyebrow">Practice readiness</div><div class="readiness-number">"+ready+'%</div></div><div class="bar"><i style="width:'+ready+'%"></i></div><p class="muted">A practice indicator based on recorded activity. It is not a pass/fail decision.</p></div><div class="modules"><button class="card module" data-mode="mcq"><span class="tag">01</span><h3>Question Challenge</h3><p>20 questions from the approved KSB bank.</p><span class="muted">Start challenge <span class="arrow">→</span></span></button><button class="card module" data-mode="discussion"><span class="tag">02</span><h3>Professional Discussion</h3><p>Answer using your phone's normal speech-to-text keyboard. Five target concepts are checked automatically.</p><span class="muted">Start discussion <span class="arrow">→</span></span></button><button class="card module" data-mode="practical"><span class="tag">03</span><h3>Workshop Practical</h3><p>Complete a 3–4 hour workshop build, inspect it and enter your measurements and marks.</p><span class="muted">Start practical <span class="arrow">→</span></span></button></div>')}

function questionCard(q){return '<div class="qmeta"><span>QUESTION '+(index+1)+' OF '+questions.length+"</span>"+badge(q[0])+'</div><div class="card question-card"><div class="question-focus"><div class="eyebrow">'+(q[0][0]==="K"?"KNOWLEDGE":q[0][0]==="S"?"SKILL":"BEHAVIOUR")+" · "+esc(q[0])+'</div><h1>'+esc(q[1])+'</h1></div><div class="answers">'+shuffle(q[2]).map((o,i)=>'<button class="answer" data-answer="'+encodeURIComponent(o)+'"><span class="letter">'+String.fromCharCode(65+i)+'</span><span>'+esc(o)+"</span></button>").join("")+"</div></div>"}
function mcq(){if(index>=questions.length){const pct=Math.round(score/questions.length*100);store[course]??={};store[course].m=Math.max(store[course].m||0,pct/100);localStorage.setItem("epa-practice",JSON.stringify(store));shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><section class="hero result"><div class="eyebrow">Challenge complete</div><h1>'+score+" / "+questions.length+'</h1><p>Your practice score was '+pct+"%.</p></section><div class="card result-card"><div class="stats"><div class="stat"><b>"+pct+'%</b><span>Score</span></div><div class="stat"><b>'+questions.length+'</b><span>Questions</span></div><div class="stat"><b>'+records().length+'</b><span>KSB questions</span></div></div><button class="btn" data-mode="mcq">New challenge</button></div>');return}current=questions[index];shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><div class="question">'+questionCard(current)+"</div>")}

const STOP=new Set("a an and are as at be by can could did do does for from how i if in is it of on or should that the their them they this to what when which with would you your into using used use was were will why".split(" "));
function tokens(text){return String(text).toLowerCase().replace(/[^a-z0-9°.+\-/ ]/g," ").split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)&&!/^[0-9]+$/.test(x))}
function discussionKeywords(q){const out=[];[...tokens(q[2][0]),...tokens(q[1])].forEach(t=>{if(!out.includes(t))out.push(t)});return out.slice(0,5)}
function discussion(){current=current||shuffle(records())[0];const found=current.discussionScore?.found||[];shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><div class="question"><div class="qmeta"><span>PROFESSIONAL DISCUSSION</span>'+badge(current[0])+'</div><div class="card question-card"><div class="eyebrow">'+(current[0][0]==="K"?"KNOWLEDGE":current[0][0]==="S"?"SKILL":"BEHAVIOUR")+" · "+esc(current[0])+'</div><h1>'+esc(current[1])+'</h1><p class="muted">Use your phone keyboard microphone to dictate your answer. Five target concepts are checked after you submit. The target concepts are not shown while you answer.</p><textarea id="answer" autocapitalize="sentences" autocomplete="off" placeholder="Tap here, then tap the microphone on your phone keyboard…">'+esc(current.answer||"")+'</textarea><div class="discussion-tip"><b>How to answer</b><span>Explain what you would do, why you would do it and use relevant construction terminology.</span></div><div class="row between"><button class="btn secondary" id="speak">Read question aloud</button><button class="btn" id="scoreDiscussion">Submit answer</button></div>'+(current.discussionScore?'<div class="feedback"><b>'+current.discussionScore.score+" / 5 points</b><br>"+found.map(x=>"✓ "+esc(x)).join("<br>")+(current.discussionScore.missed.length?"<br>"+current.discussionScore.missed.map(x=>"✗ "+esc(x)).join("<br>"):"")+"</div>":"")+"</div></div>")}
function scoreDiscussion(){const answer=($("#answer")?.value||"").trim();if(!answer){alert("Enter an answer first.");return}current.answer=answer;const lower=answer.toLowerCase();const keys=discussionKeywords(current);const found=keys.filter(k=>lower.includes(k.toLowerCase()));const missed=keys.filter(k=>!found.includes(k));current.discussionScore={score:found.length,found,missed};store[course]??={};store[course].d=Math.max(store[course].d||0,found.length/5);localStorage.setItem("epa-practice",JSON.stringify(store));discussion()}
function speak(t){if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="en-GB";u.rate=.92;speechSynthesis.speak(u)}}

function practical(){const task=EPA_PRACTICALS[course];current=current||task;const checks=task.checks;const saved=current.marks||{};shell('<button class="btn ghost" data-course-home>‹ '+COURSE[course]+'</button><div class="sectionhead"><div><div class="eyebrow">WORKSHOP PRACTICAL · '+esc(task.duration)+'</div><h2>'+esc(task.title)+'</h2><p class="muted">'+esc(task.basis)+'</p></div></div><div class="practical"><div class="card"><div class="tag">Task brief</div>'+task.brief.map((x,i)=>'<p class="brief-item"><b>'+(i+1)+'.</b> '+esc(x)+"</p>").join("")+'</div><div class="card"><div class="tag">Before you start</div><p class="muted">This is a workshop activity. Follow your college/employer RAMS, drawings, specifications and manufacturer instructions. The app does not replace an assessor.</p><label class="check"><input type="checkbox" id="started" '+(current.started?"checked":"")+'><span>I have read the task and completed the required workshop safety checks.</span></label></div><div class="card mark-card"><div class="tag">Final inspection</div><h3>Record your results</h3><p class="muted">For measurements, enter the value you actually measured. For quality checks, award yourself 0, 1 or 2.</p>'+checks.map((c,i)=>c.kind==="measure"?'<div class="mark-row"><div><b>'+(i+1)+". "+esc(c.label)+'</b><small>Target '+esc(c.target)+" "+esc(c.unit)+" · tolerance ±"+esc(c.tol)+" "+esc(c.unit)+(c.note?" · "+esc(c.note):"")+'</small></div><input class="measure" inputmode="decimal" data-mark="'+i+'" value="'+esc(saved[i]?.value??"")+'" placeholder="'+esc(c.unit)+'"></div>':'<div class="mark-row"><div><b>'+(i+1)+". "+esc(c.label)+'</b><small>0 = not achieved · 1 = partly achieved · 2 = achieved</small></div><select data-mark="'+i+'"><option value="">Mark</option><option value="0" '+(saved[i]?.value==="0"?"selected":"")+'>0</option><option value="1" '+(saved[i]?.value==="1"?"selected":"")+'>1</option><option value="2" '+(saved[i]?.value==="2"?"selected":"")+'>2</option></select></div>').join("")+'<button class="btn" id="calculatePractical">Calculate result</button></div><div class="card practical-result" id="practicalResult"></div></div>')}
function calculatePractical(){const task=EPA_PRACTICALS[course];const marks={};let earned=0,max=0,complete=true;task.checks.forEach((c,i)=>{const el=document.querySelector('[data-mark="'+i+'"]');if(!el||el.value===""){complete=false;return}if(c.kind==="measure"){const v=Number(el.value);if(!Number.isFinite(v)){complete=false;return}const ok=Math.abs(v-c.target)<=c.tol;marks[i]={value:el.value,points:ok?2:0};earned+=ok?2:0;max+=2}else{const v=Number(el.value);marks[i]={value:el.value,points:v};earned+=v;max+=c.max}});if(!complete){alert("Complete every mark before calculating the result.");return}current=task;current.marks=marks;current.started=$("#started")?.checked||false;store[course]??={};store[course].p=Math.max(store[course].p||0,earned/max);store[course].practical={earned,max,marks,date:new Date().toISOString()};localStorage.setItem("epa-practice",JSON.stringify(store));const pct=Math.round(earned/max*100);$("#practicalResult").innerHTML='<div class="tag">Practice result</div><div class="practical-score">'+pct+"%</div><p><b>"+earned+" / "+max+' points</b></p><p class="muted">This is a self-recorded workshop practice result, not an official EPA grade.</p><div class="result-note">'+(pct>=80?"Review any missed checks before repeating the build.":"Repeat the task and focus on the checks that did not meet the required tolerance or standard.")+'</div><button class="btn secondary" id="reopenPractical">Review mark sheet</button>';$("#reopenPractical").onclick=practical}
function bind(){document.querySelectorAll("[data-course]").forEach(b=>b.onclick=()=>{course=b.dataset.course;courseHome()});document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>start(b.dataset.mode));document.querySelectorAll("[data-home]").forEach(b=>b.onclick=home);document.querySelectorAll("[data-course-home]").forEach(b=>b.onclick=courseHome);document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>{const picked=decodeURIComponent(b.dataset.answer);const ok=picked===current[2][0];b.classList.add(ok?"correct":"wrong");if(ok)score++;document.querySelectorAll("[data-answer]").forEach(x=>x.disabled=true);setTimeout(()=>{index++;mcq()},450)});$("#speak")?.addEventListener("click",()=>speak(current[1]));$("#answer")?.addEventListener("input",e=>current.answer=e.target.value);$("#scoreDiscussion")?.addEventListener("click",scoreDiscussion);$("#calculatePractical")?.addEventListener("click",calculatePractical)}
function start(m){mode=m;index=0;score=0;current=null;if(m==="mcq"){questions=shuffle(records()).slice(0,20);mcq()}else if(m==="discussion"){current=shuffle(records())[0];discussion()}else{current=EPA_PRACTICALS[course];practical()}}
home();