const EPA_MATHS_QUESTIONS=[
["Fractions, Decimals and Percentages","A trade merchant prices a pack of timber at £150 before applying a 20% trade discount.",["£110.00","£120.00","£130.00","£140.00"],"£120.00","To find a 20% discount, calculate 20% of £150 (£30) and subtract it from the original total (£150 - £30 = £120).","If an item costs £40 and has a 25% discount (£10 off), what is the final price?",["£30","£35"],"£30"],
["Fractions, Decimals and Percentages","An apprentice completes 18 out of a total target of 24 flooring boards. What percentage of the target has been completed?",["65%","70%","75%","80%"],"75%","Divide the part by the total (18 ÷ 24 = 0.75) and multiply by 100 to get 75%.","If you score 3 out of 4 on a test, what is that as a percentage?",["75%","60%"],"75%"],
["Fractions, Decimals and Percentages","A material budget increases from £500 to £550 over the year. What is the percentage increase in the budget?",["5%","10%","15%","20%"],"10%","Find the increase (£50), divide it by the original amount (£500), and multiply by 100 (50 ÷ 500 = 0.10, or 10%).","If a price goes up by £10 from an original £100, what is the percentage increase?",["10%","5%"],"10%"],
["Ratio, Proportion and Scaling","A mortar mix uses cement and sand in the ratio 1 : 3. If you use 3 bags of cement, how many bags of sand do you need?",["6 bags","8 bags","9 bags","12 bags"],"9 bags","For every 1 part of cement, you need 3 parts of sand. Multiply the cement amount by 3 (3 × 3 = 9).","If the ratio is 1 : 2 and you use 4 bags of cement, how much sand do you need?",["8 bags","6 bags"],"8 bags"],
["Ratio, Proportion and Scaling","If 2 workers can complete a site hoarding installation in 6 days, how many days will it take 4 workers to complete the exact same task working at the same rate?",["2 days","3 days","4 days","12 days"],"3 days","This is inverse proportion. Multiply workers by days to find total worker-days (2 × 6 = 12), then divide by the new worker count (12 ÷ 4 = 3 days).","If 2 workers take 4 days to paint a wall, how many days for 4 workers?",["2 days","4 days"],"2 days"],
["Ratio, Proportion and Scaling","On an architectural scale drawing, a dimension of 20 mm represents an actual length of 1 metre (1,000 mm). What is the scale ratio?",["1 : 20","1 : 50","1 : 100","1 : 200"],"1 : 50","Divide the actual measurement (1,000 mm) by the drawing measurement (20 mm) to find the scale factor (1,000 ÷ 20 = 50), giving a ratio of 1 : 50.","If 10 mm represents 100 mm, what is the scale ratio?",["1 : 10","1 : 20"],"1 : 10"],
["Measures, Shape and Space","What is the area of a rectangular workshop floor measuring 6 metres long by 4 metres wide?",["10 m²","20 m²","24 m²","36 m²"],"24 m²","Area is calculated by multiplying length by width (6 × 4 = 24), not by adding them together.","What is the area of a rug measuring 3 m by 3 m?",["9 m²","6 m²"],"9 m²"],
["Measures, Shape and Space","A room measures 5 m long and 3 m wide. What is the total perimeter of the room?",["8 m","15 m","16 m","25 m"],"16 m","Perimeter is the total distance around the outside. Add all four sides together (5 + 5 + 3 + 3 = 16 m).","What is the perimeter of a square with sides measuring 2 m?",["8 m","6 m"],"8 m"],
["Measures, Shape and Space","What is the volume of a rectangular storage box measuring 2 m long, 1 m wide, and 1.5 m high?",["3.0 m³","4.5 m³","6.0 m³","7.5 m³"],"3.0 m³","Volume is length × width × height (2 × 1 × 1.5 = 3.0 m³).","What is the volume of a box measuring 2 m × 2 m × 2 m?",["8 m³","6 m³"],"8 m³"],
["Handling Data and Statistics","An apprentice records the following daily timber cutting times in minutes: 30, 40, 50, 40, 60. What is the median time?",["35 minutes","40 minutes","45 minutes","50 minutes"],"40 minutes","Put the numbers in order from smallest to largest (30, 40, 40, 50, 60). The middle value is 40.","Find the median of these numbers: 10, 20, 30.",["20","10"],"20"],
["Handling Data and Statistics","A builder records daily delivery delays in minutes over 4 days: 10, 20, 0, 10. What is the mean (average) delay?",["5 minutes","10 minutes","15 minutes","20 minutes"],"10 minutes","Add all values together (10 + 20 + 0 + 10 = 40) and divide by the number of days (4), giving 40 ÷ 4 = 10.","Find the mean of 2, 4, and 6.",["4","6"],"4"],
["Handling Data and Statistics","A set of test scores ranges from a minimum of 45 to a maximum of 85. What is the range of the dataset?",["30","40","45","130"],"40","The range is the highest value minus the lowest value (85 - 45 = 40).","What is the range if the highest score is 50 and the lowest score is 20?",["30","20"],"30"]
];